- manifests/00-cluster-role.yaml
/cc @openshift/sig-network-edge 
@pravisankar  PTAL thx
> Allow role to get objects for getting installer config map.

- Gopkg.lock
- config/config.yaml
- pkg/stub/handler.go
- pkg/util/config.go
- vendor/github.com/apparentlymart/go-cidr/LICENSE
- vendor/github.com/apparentlymart/go-cidr/cidr/cidr.go
- vendor/github.com/apparentlymart/go-cidr/cidr/wrangling.go
Configure the operator to use the same DNS IP used by the kubelet
jira ticket: https://jira.coreos.com/browse/NE-86
/cc @openshift/sig-network-edge    
PTAL  Thx
*Edited* Removed old test info
> Use cluster dns ip address from install config if "available"

- Makefile
- pkg/manifests/manifests.go
Add makefile targets to build local images and verifying go code with gofmt.
Plus fix the gofmt issue that this found. 
@pravisankar  PTAL Thx
/cc @openshift/sig-network-edge
> Makefile changes to add targets for building local image and gofmt verification

- manifests/0000_08_cluster-dns-operator_02-deployment.yaml
https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/#concepts has docs
that define a toleration that tolerates evrything
```
An empty key with operator Exists matches all keys, values and effects which means this will tolerate everything.
```
/cc @ramr
> manifests: allow dns operator to schedule on any node

- hack/release-local.sh
Cherry-pick https://github.com/openshift/cluster-ingress-operator/pull/56 and https://github.com/openshift/cluster-ingress-operator/pull/57.
Fix the `cp` command in `release-local.sh` to copy the manifest files directly into the temporary directory rather than copying the `manifests/` directory as a subdirectory of the temporary directory.  This change causes the subsequent sed command to overwrite the `0000_08_cluster-dns-operator_02-deployment.yaml` file.
Before this commit, on some operating systems, the cp command in `release-local.sh` was copying the `manifests/` directory under the temporary directory, and the subsequent sed command was creating a second `0000_08_cluster-dns-operator_02-deployment.yaml` file in the temporary directory, as shown below:
/tmp/tmp.tXJWHA970j
├── …
> release-local.sh fixes

- pkg/stub/handler.go
- Creating dns service and ignoring if exists is not sufficient as api server
can throw 'provided IP is already allocated' error.
> Fix dns service reconciliation

- Makefile
- test/e2e/operator_test.go
Add baseline end-to-end tests for cluster-dns-operator.
* `Makefile` (`test-e2e`): Add target.
* `test/e2e/operator_test.go`: Add tests.
This commit is related to NE-97.
https://jira.coreos.com/browse/NE-97
> Add baseline end-to-end tests

- README.md
Bugs are tracked in Bugzilla. GitHub issues are disabled for the repository, so make a note in the README to redirect users to Bugzilla.
> docs/readme: Add Bugzilla issue reporting link

- manifests/0000_08_cluster-dns-operator_03-cluster-operator.yaml
This makes the operator conform to:
https://github.com/openshift/cluster-version-operator/blob/master/docs/dev/clusteroperator.md
> manifests: Add ClusterOperator resource

- manifests/0000_08_cluster-dns-operator_02-deployment.yaml
- manifests/0000_08_cluster-dns-operator_03-cluster-operator.yaml
- pkg/stub/status.go
Every operator shall report a version with name=operator whose value is equal to the RELEASE_VERSION provided by the cluster version operator.
will be enforced via [openshift/origin#22156](https://github.com/openshift/origin/pull/22156)
> status: report cluster operator version from payload

- cmd/cluster-dns-operator/main.go
- hack/uninstall.sh
- manifests/0000_08_cluster-dns-operator_03-cluster-operator.yaml
- pkg/operator/config.go
- pkg/stub/status.go
- version/version.go
- Removed version/version.go, no longer used.
Follow up pr for https://github.com/openshift/cluster-dns-operator/pull/78
> Check RELEASE_VERSION env existence before starting the reconciliation.

- manifests/0000_08_cluster-dns-operator_00-cluster-role.yaml
- pkg/stub/handler.go
- pkg/stub/status.go
- pkg/stub/status_test.go
- test/e2e/operator_test.go
- Use get resource and if not found, create the resource pattern for all DNS resources
- Added log info messages for create and delete resources related to DNS
- Update daemonset when the operator publishes new core dns image
- Added test cases for validating coreDNS image update and operator version update
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1673989
> Allow dns operator to update coreDNS image

- Makefile
Previously, `make build` would only build the cluster dns operator bin for linux. This prevents dev's from building and running the operator on a non-Linux machine.
This commit removes static `GOOS=linx` Makefile references, allowing the build to use the local OS. Additionally, this provides parity with the cluster-ingress-operator.
/hold
> Removes static GOOS reference from Makefile

- cmd/dns-operator/main.go
This import was added accidentally.
* `cmd/dns-operator/main.go`: Delete import of the client-go GCP auth plug-in.
> Delete registration of client-go GCP auth plug-in

- pkg/operator/controller/controller.go
- pkg/operator/controller/dns_status.go
- pkg/operator/controller/dns_status_test.go
- pkg/operator/controller/status.go
- pkg/operator/controller/status_test.go
- test/e2e/operator_test.go
Previously, status conditions for the `dns.operator.openshift.io/v1` resource were not implemented.
This commit does the following:
- Implements `Degraded`, `Progressing` and `Available` status conditions for `dns.operator.openshift.io/v1`.
- Refactors cluster-dns-operator `Degraded` status condition to be calculated from the the availability of `ClusterIP`.
- Refactors cluster-dns-operator `Progressing` and `Available` status conditions to be calculated from the `dns.operator.openshift.io/v1` `Available` condition.
- Replaces deployment logic from cluster-dns-operator unit tests with `dns.operator.openshift.io/v1` `Available` conditions.
- Adds `dns.operator.openshift.io/v1` status condition unit tests.
> Bug 1690342: Initial DNS status conditions implementation

- pkg/operator/controller/dns_status.go
- pkg/operator/controller/dns_status_test.go
https://github.com/openshift/cluster-dns-operator/pull/88 added dns status conditions. Initially the PR included status.version as part of the Progressing condition calculation, which required `computeDNSStatusConditions` to contain a reconciler pointer receiver. It was later decided to include status.version calculation in a separate PR, but the pointer was not removed.
> Removes receiver from computeDNSStatusConditions func

- hack/release-local.sh
https://github.com/openshift/cluster-dns-operator/pull/101 introduced a bug by updating the operator deployment manifest filename without updating the reference in release-local.sh. This PR updates the filename in release-local.sh, allowing local releases to properly build
> Fixes operator deployment filename in release-local.sh

- cmd/dns-operator/main.go
- manifests/0000_70_dns-operator_03-cluster-operator.yaml
- pkg/operator/controller/status.go
- pkg/operator/controller/status_test.go
- Always report 'operator' version irrespective of available condition.
- For upgrades, report old versions until the new version is fully applied.
> Bug 1705032: Fix updating versions for dns cluster operator

- hack/release-local.sh
- manifests/0000_70_dns-operator_03-cluster-operator.yaml
- As per the spec[1], ClusterOperator resource must be created by the operator.
[1] https://github.com/openshift/cluster-version-operator/blob/master/docs/dev/clusteroperator.md#how-clusterversionoperator-handles-clusteroperator-in-release-imagehttps://github.com/openshift/cluster-version-operator/blob/master/docs/dev/clusteroperator.md#how-clusterversionoperator-handles-clusteroperator-in-release-image
> Fix hack/release.sh: Skip ClusterOperator resource creation

- manifests/0000_70_dns-operator_02-deployment.yaml
In 4.1, we have taint-based evictions enabled. This changes logic in the node lifecycle controller in the kube-controller-manager significantly.
Historically, the node lifecycle controller would directly evict pods from node that had a Ready condition of False or Unknown after a pod eviction timeout set by the --pod-eviction-timeout flag on the kube-controller-manager. This setting applied to all pods cluster-wide. The default was 5m.
With taint-based evictions, all the node lifecycle controller does is taint the node with node.kubernetes.io/unreachable and/or node.kubernetes.io/not-ready taint with NoExecute effect. This would normally result in the immediate eviction of all pods that don't tolerate those taints, breaking the old behavior with pod eviction timeouts. Enter …
> Bug 1706204: Fix tolerations

- pkg/operator/controller/status.go
Add related dnses to operator status to ensure dnses are captured
by must-gather.
`oc adm must-gather` output:
```
$ tree cluster-scoped-resources/operator.openshift.io/dnses/
cluster-scoped-resources/operator.openshift.io/dnses/
└── default.yaml
0 directories, 1 file
```
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1717734
TODO
> Bug 1717734: status: add related dnses to operator status

- pkg/operator/controller/controller.go
Use a controller name which is always a valid metric name, allowing the
controller-runtime to successfully register all metrics which incorporate
the controller's name.
TODO:
> metrics: fix metrics registration bug

- Dockerfile.rhel7
Follow-up to https://github.com/openshift/cluster-dns-operator/pull/115.
* `Dockerfile.rhel7`: Use the golang-1.12 builder image.
> Dockerfile.rhel7: Use golang-1.12

- manifests/0000_70_dns-operator_03-cluster-operator.yaml
Add version info to manifest so the CVO can identify the operator's
version keys in the clusteroperator status.
> Bug 1726449: manifests: add version information

- manifests/0000_70_dns-operator_02-deployment.yaml
Remove a redundant 'node.kubernetes.io/not-ready' toleration on the operator
deployment manifest.
> Bug 1722341: remove duplicate toleration key from operator deployment

- pkg/operator/controller/status.go
Simplify relatedObjects computation by omitting resource names.
https://jira.coreos.com/browse/NE-218
> syncOperatorStatus: Simplify relatedObjects

- pkg/operator/controller/dns_status.go
- pkg/operator/controller/dns_status_test.go
status: prevent degraded status flapping on rollout
The current DNS degraded status calculation doesn't incorporate time. If at any
time of observation the number of desired daemonset available replicas diverges
from the desired scheduled replicas, the CoreDNS daemonset is instantly
considered degraded. This results in degraded true/false flapping when the
operator aggregates the DNS status during a daemonset rollout.
This seems like a poor meausure of degraded, because most of the time this
condition arises during a rollout when QoS is not seriously affected. A better
way might be to incorprate progressing time into the calculation, and that is
something we should probably do, but the solution is a little more complex.
This patch should provide a good improvement in the meantime by only …
> status: prevent degraded status flapping on rollout

- manifests/0000_70_dns-operator_00-cluster-role.yaml
- manifests/0000_70_dns-operator_00-namespace.yaml
- manifests/0000_70_dns-operator_01-service.yaml
- manifests/0000_70_dns-operator_02-deployment.yaml
- manifests/0000_90_dns-operator_00_prometheusrole.yaml
- manifests/0000_90_dns-operator_01_prometheusrolebinding.yaml
- manifests/0000_90_dns-operator_02_servicemonitor.yaml
- manifests/image-references
The operator exposes metrics, but they are not collected.  Configure Prometheus to collect these metrics.
* `manifests/0000_70_dns-operator_00-namespace.yaml`: Add a label for `openshift-monitoring`.
* `manifests/0000_70_dns-operator_02-deployment.yaml`: Add the metrics port.
* `manifests/0000_70_dns-operator_04-service.yaml`: New file.  Define a metrics service.
* `manifests/0000_90_dns-operator_00_prometheusrole.yaml`:  New file.  Define a role that grants access to services, endpoints, and pods.
* `manifests/0000_90_dns-operator_01_prometheusrolebinding.yaml`:  New file.  Bind the `prometheus-k8s` service account to the new role.
* `manifests/0000_90_dns-operator_02_servicemonitor.yaml`: New file.  Define a service monitor for the new service.
> NE-76: Integrate operator metrics with Prometheus

- pkg/operator/controller/controller_dns_daemonset.go
- pkg/operator/controller/controller_dns_daemonset_test.go
Follow-up to #140.
* `pkg/operator/controller/controller_dns_daemonset.go` (`daemonsetConfigChanged`): Compare tolerations using go-cmp and the new `cmpTolerations` function.
(`cmpTolerations`): New function.
* `pkg/operator/controller/controller_dns_daemonset_test.go` (`toleration`): New variable.  Dummy toleration for testing.
(`TestDaemonsetConfigChanged`): Add a test case to verify that `deploymentConfigChanged` detects updates to `.spec.template.spec.tolerations`.
----
@ironcladlou
> Bug 1778529: daemonsetConfigChanged: Check tolerations

- .github/ISSUE_TEMPLATE/config.yml
- README.md
Change the component from "Routing" to "DNS".  Delete the version, which was "4.0.0", which does not exist; it is better not to specify a default version anyway as we cannot know the version against which the user is reporting an issue.
* `README.md`: Fix Bugzilla link.
* `.github/ISSUE_TEMPLATE/config.yml`: New file.  Add links to Bugzilla and documentation.
> Fix Bugzilla link and add GitHub issue template configuration

- pkg/operator/controller/controller_dns_daemonset.go
- pkg/operator/controller/controller_dns_daemonset_test.go
- pkg/operator/controller/controller_service_monitor_test.go
Fixes the potential for a false positive unit test in `pkg/operator/controller/controller_service_monitor_test.go`.
Also adds the `kube-rbac-proxy` name to the DNS daemonset config changed function, as well as corresponding unit test.
> Bug 1826885: DNS Service Monitor & Daemonset fixes

- test/e2e/operator_test.go
- test/e2e/utils.go
Adds an end-to-end test for the DNS Forwarding [feature](https://github.com/openshift/enhancements/blob/master/enhancements/dns/plugins.md).
In support of [NE-257](https://issues.redhat.com/browse/NE-257)
/assign @ironcladlou @knobunc 
/cc @Miciah @frobware
> Bug 1826996: Adds DNS Forwarding e2e Test

- pkg/operator/controller/status.go
The DNS operator `Progressing` status condition message should reflect a "progressing", not an "available" message.
> Bug 1838266: Updates Progressing status condition message

- pkg/operator/controller/status.go
Follow-up to #109.
* `pkg/operator/controller/status.go` (`computeOperatorDegradedCondition`): Check total number of `dns` resources, not the available number, before reporting no DNS resource exists.
---
I noticed the erroneous error reporting in https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_router/113/pull-ci-openshift-router-master-e2e-aws/373:
```
level=error msg="Cluster operator dns Degraded is True with NoDNS: No DNS resource exists"
```
The operator's logs showed that it had created the resource, and CI artifacts showed that the daemonset existed but had no available replicas.
> Bug 1835725: computeOperatorDegradedCondition: Fix "NoDNS" check

- manifests/0000_90_dns-operator_03_prometheusrules.yaml
Adds a couple of CoreDNS alert rules.
Still deciding if using the CVO is the best way to apply the `PrometheusRule` object. For now I think it is. If anyone has any input for CVO vs ~OLM~ using the DNS operator for managing DNS alert rules, please feel free to chime in. 
- CoreDNSPanicCount
Triggers if CoreDNS panics
- CoreDNSHealthCheckSlow
Triggers if CoreDNS health checks are significantly slowing down
> NE-169: Add simple CoreDNS Prometheus alert rules

- README.md
* `README.md`: Mention that the operator allows some `Corefile` configuration.  Expand the "How it works" section.
> Add more description of how the operator works

- pkg/operator/controller/controller.go
- pkg/operator/controller/controller_cluster_role.go
- pkg/operator/controller/controller_dns_configmap.go
- pkg/operator/controller/controller_dns_daemonset.go
- pkg/operator/controller/controller_dns_service.go
- pkg/operator/controller/controller_service_monitor.go
Switches all `ensureDNS<thing>` functions in `pkg/operator/controller`
to use a `have<thing>` boolean rather than manually checking if
`<thing> != nil`.
@Miciah mentioned that this is the pattern the cluster-ingress-operator tries to follow, so the cluster-dns-operator should do the same.
> controller: Rework boolean logic for consistency

- pkg/operator/controller/controller_dns_daemonset_test.go
Adds a unit test to the DNS daemonset test to cover https://github.com/openshift/cluster-dns-operator/blob/master/pkg/operator/controller/controller_dns_daemonset.go#L213. Adding a new container to the daemonset is something that has recently occurred (#163), so this test would be helpful.
> DNS Daemonset: Add unit test

- pkg/operator/controller/controller_dns_daemonset.go
- pkg/operator/controller/controller_dns_daemonset_test.go
- pkg/operator/controller/controller_dns_service.go
- pkg/operator/controller/controller_dns_service_test.go
When comparing services to determine whether an update is required, treat implicit and explicit default values as equal.
Before this commit, the update logic would keep trying to revert the default value that the API set for the service's session affinity or type.
* `pkg/operator/controller/controller_dns_service.go` (`serviceChanged`): Use the new `cmpServiceAffinity` and `cmpServiceType` functions so that two services are considered equal if the only difference between them is that one does not specify the session affinity or type and the other service has the default values.
(`cmpServiceAffinity`, `cmpServiceType`): New function.
* `pkg/operator/controller/controller_dns_service_test.go`: (`TestDNSServiceChanged`): Verify that `serviceChanged` returns false if the only mutation is that …
> Bug 1842741: Fix serviceChanged and daemonsetConfigChanged

- manifests/0000_90_dns-operator_03_prometheusrules.yaml
This pr updates the existing `CoreDNSPanicking` metric and add alerts for `CoreDNSErrorsHigh`. For more context, please check https://coreos.slack.com/archives/CCH60A77E/p1595256269123600
> Port coredns errors alert

- pkg/operator/controller/controller.go
`pkg/operator/controller/controller.go`: Adds `ensureServiceIP()` to ensure the DNS service IP is available for allocation before assigning it to `spec.ClusterIP`.
/assign @Miciah @knobunc
> Bug 1813062: ensures service IP is allocatable

- pkg/operator/controller/status/controller.go
- test/e2e/operator_test.go
The dns cluster operator is fed the DNS operator's namespace in pkg/operator/controller/status/controller.go. This commit fixes a regression brought in by https://github.com/openshift/cluster-dns-operator/pull/187 in which the cluster operator is given a reference to the "dns" namespace, which does not exist. This commit instead gives the cluster operator a reference to the correct operator namespace set at run time.
--- 
This regression affects must-gather, but could also have potentially unknown consequences since the cluster operator resource is pointing to a nil namespace.
> Bug 1882323: Fix operator namespace in clusteroperator related resources

- Dockerfile
Updating ose-cluster-dns-operator builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/ose-cluster-dns-operator.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.
> Updating ose-cluster-dns-operator builder & base images to be consistent with ART

- cmd/dns-operator/main.go
- pkg/operator/controller/controller_dns_configmap.go
- pkg/operator/controller/controller_dns_configmap_test.go
Configure the operator's metrics handler and the CoreDNS metrics plugin to listen on 127.0.0.1 only.
Before this change, metrics were exposed on ports 9153 and 60000, without authentication.  Although the pod spec does not advertise ports 9153 or 60000, the ports were still accessible outside the pod.  After this change, ports 9153 and 60000 are inaccessible outside the pod, so the only way to get metrics is by connecting to port 9154 (for CoreDNS metrics) or port 9393 (for operator metrics) and authenticating with kube-rbac-proxy.
* `cmd/dns-operator/main.go` (`main`): Configure metrics to listen on 127.0.0.1:60000.
* `pkg/operator/controller/controller_dns_configmap.go` (`corefileTemplate`): Configure metrics to listen on 127.0.0.1:9153.
* …
> Bug 1896923: Configure CoreDNS metrics plugin to use localhost

- test/e2e/operator_test.go
**Block on TestCoreDNSImageUpgrade image revert**
TestCoreDNSImageUpgrade: Ensure that the CoreDNS image change for default DNS is completely reverted before moving onto the next test.
TestDNSForwarding: Ensure that DNS pods are all available before verifying Corefile contents from each DNS pod. Also, log pod status if a given pod's Corefile doesn't meet the test's expectations. 
This commit enhances the DNS operator tests to resolve BZ#1908891, in which TestDNSForwarding is noted as very flakey due to TestDNSForwarding's image revert rollout not blocking the premature execution of TestDNSFowarding.
> Bug 1908891: test/e2e: Block on TestCoreDNSImageUpgrade image revert

- test/e2e/operator_test.go
**test/e2e/operator_test.go:** 
Re-enable TestCoreDNSImageUpgrade by adding a
cluster version override for the DNS operator deployment. This override
allows TestCoreDNSImageUpgrade to safely modify the DNS deployment
(specifically the operator's container image field) without contention
from the CVO. The cluster version override is removed at the end of the
test via a `defer` block.
> Bug 1912522: test/e2e: Re-enable TestCoreDNSImageUprade

- pkg/operator/controller/controller_dns_configmap.go
- pkg/operator/controller/controller_dns_configmap_test.go
https://github.com/coredns/coredns/pull/3737 removed the unused
`upstream` kubernetes plugin option from the CoreDNS corefile parser.
Starting in CoreDNS v1.7, corefiles that have the `upstream` option will
throw an error. This change should not affect functionality since the
`upstream` option has been ignored since CoreDNS v1.5. The
aforementioned upstream CoreDNS PR merely requires that the
`upstream` option be removed for the kubernetes plugin section of a
corefile.
---
This PR will unblock https://github.com/openshift/coredns/pull/52 and is therefore a part of https://issues.redhat.com/browse/NE-514.
> NE-514: Corefile: Drop deprecated kubernetes `upstream` option

- pkg/operator/controller/controller_dns_configmap.go
- pkg/operator/controller/controller_dns_configmap_test.go
Before this change, the operator configured CoreDNS's cache plugin with a maximum TTL of 30 seconds, meaning cache entries expired after 30 seconds (or sooner, depending on the TTL from the upstream resolver).  This change increases the maximum TTL to 900 seconds to reduce load on upstream resolvers.
* `pkg/operator/controller/controller_dns_configmap.go` (`corefileTemplate`): Configure the cache plugin with a 900-second maximum TTL.
* `pkg/operator/controller/controller_dns_configmap_test.go` (`TestDesiredDNSConfigmap`): Update to expect the new value.
> Bug 1933761: Set CoreDNS's cache's maximum TTL to 900 seconds

- pkg/operator/controller/controller_dns_configmap.go
- pkg/operator/controller/controller_dns_configmap_test.go
Before this change, the operator did not enable the "errors" plugin in server blocks for custom upstream resolvers.  As a consequence, failures from upstream resolvers were not logged.  This change enables the errors plugin for all server blocks.
* `pkg/operator/controller/controller_dns_configmap.go` (`corefileTemplate`): Add the errors plugin to server blocks for custom upstream resolvers.
* `pkg/operator/controller/controller_dns_configmap_test.go` (`TestDesiredDNSConfigmap`): Update to expect the errors plugin in all server blocks.
> Bug 1934905: Enable errors plugin for custom upstream resolvers

- manifests/0000_90_dns-operator_03_prometheusrules.yaml
https://github.com/openshift/coredns/pull/52 updates openshift/coredns to use coredns/coredns v1.8.1. CoreDNS v1.7.0 added breaking metrics renaming changes. This commit changes the following metric names to match the naming used in CoreDNS v1.7.0 and beyond:
* `coredns_dns_response_rcode_count_total` -> `coredns_dns_responses_total`
* `coredns_panic_count_total` -> `coredns_panics_total`
See https://coredns.io/2020/06/15/coredns-1.7.0-release/ for more context.
---
Prerequisites:
This PR is in support of https://issues.redhat.com/browse/NE-515
> NE-515: Alerts: Update prometheus alert rules for CoreDNS v1.8.z

- pkg/operator/controller/controller_cluster_role.go
- pkg/operator/controller/controller_dns_configmap.go
- pkg/operator/controller/controller_dns_daemonset.go
- pkg/operator/controller/controller_dns_daemonset_test.go
- pkg/operator/controller/controller_dns_service.go
- pkg/operator/controller/controller_dns_service_test.go
- pkg/operator/controller/controller_service_monitor.go
This PR improves log output when reconciling managed resources to log the diff between the current and updated resources when performing an update.
* `pkg/operator/controller/controller_cluster_role.go` (`updateDNSClusterRole`):
* `pkg/operator/controller/controller_dns_daemonset.go` (`updateDNSDaemonSet`):
* `pkg/operator/controller/controller_dns_service.go` (`updateDNSService`):
* `pkg/operator/controller/controller_service_monitor.go` (`updateDNSServiceMonitor`): Log the diff between the current and updated resources when performing an update.
When comparing daemonsets to determine whether an update is required, treat implicit and explicit default values for `terminationGracePeriodSeconds` as equal.
Before this PR, the update logic would keep trying to revert the default value that …
> Bug 1936022: Fix spurious reconciliation of DNS daemonset and service

- pkg/operator/controller/controller_dns_configmap.go
- pkg/operator/controller/controller_dns_configmap_test.go
Commit 066b3f7 bumped the max TTL for records in the CoreDNS cache to 900 seconds, including negative DNS responses such as NXDOMAIN. This max TTL applies to responses received from the cluster's upstream resolver.
This commit fixes bug 1943578 by lowering the CoreDNS cache max TTL for negative DNS responses to 30 seconds (while maintaining the new 900 second max TTL for positive responses).
Note that `9984` is the default cache size. See https://coredns.io/plugins/cache/ for more context.
This commit resolves https://bugzilla.redhat.com/show_bug.cgi?id=1943578.
pkg/operator/controller/controller_dns_configmap.go:
Configure the cache plugin with a 900 second TTL for positive records and 30 second TTL for negative records in the CoreDNS Corefile. …
> Bug 1943578: Corefile: Use 30 second max TTL for caching of negative responses

- pkg/operator/controller/controller_dns_node_resolver_daemonset.go
Replace "beta.kuberneta.io/os" with "kubernetes.io/os" in the node-resolver pods' node selector.  The old label was superseded by the new one and deprecated in Kubernetes 1.14 and subsequently removed in Kubernetes 1.19.
Follow-up to #209.
* `pkg/operator/controller/controller_dns_node_resolver_daemonset.go` (`desiredNodeResolverDaemonSet`): Change node selector from `beta.kubernetes.io/os: linux` to `kubernetes.io/os: linux`.
---
Thanks to @sgreene570 for noticing the old label!
> node-resolver: Use "kubernetes.io/os" node label

- pkg/operator/controller/dns_status.go
use same error message for Degraded/Progressing/Available conditions if len(clusterIP) == 0
> Bug 1946893: update inconsistent error message for AvailableCondition

- pkg/operator/controller/controller_dns_configmap.go
- pkg/operator/controller/controller_dns_configmap_test.go
Enable the CoreDNS bufsize plugin (https://coredns.io/plugins/bufsize/)
with a buffer size value of `1232` bytes to accomplish the following:
* Limit a requester's UDP payload size.
* Prevent UDP packet fragmentation when DNS responses are >512 bytes.
* Add an EDNS OPT pseudo RR when a client _does not_ specify one.
This commit resolves Bug 1949361, particularly via the 3rd bullet listed
above. When a DNS query bound for an upstream resolver is forwarded without
any EDNS OPT pseudo RR, the upstream resolver may send back packets that
exceed CoreDNS's UDP buffer size, resulting in a SERVFAIL response
(along with various CoreDNS errors being logged).
Note that preventing DNS packet fragmentation may mitigate potential
security vulnerabilities. See https://dnsflagday.net/2020/ for more …
> Bug 1949361: Corefile: Enable bufsize plugin for all servers

- pkg/operator/controller/controller.go
- pkg/operator/controller/controller_dns_node_resolver_daemonset.go
- pkg/operator/controller/controller_dns_node_resolver_daemonset_test.go
Configure the node-resolver daemonset with an owner reference on the dns.
The dns controller watches daemonsets in the operand namespace and enqueues reconcile requests for a daemonset's owner, so without the owner reference, events for the node-resolver daemonset are ignored.
* `pkg/operator/controller/controller.go` (`ensureDNS`): Pass `dns` to `ensureNodeResolverDaemonset`.
* `pkg/operator/controller/controller_dns_node_resolver_daemonset.go` (`ensureNodeResolverDaemonset`): Add `dns` parameter.  Pass `dns` to `desiredNodeResolverDaemonSet`.
(`desiredNodeResolverDaemonSet`): Add `dns` parameter.  Add an owner reference on the dns, so that the controller's watch on daemonsets maps updates to the node-resolver daemonset to reconcile requests for the dns.
* …
> Bug 1953280: node-resolver: Set owner reference on the dns

- pkg/operator/controller/controller_dns_configmap.go
- pkg/operator/controller/controller_dns_configmap_test.go
Enable the CoreDNS bufsize plugin (https://coredns.io/plugins/bufsize/)
with a buffer size value of `1232` bytes to accomplish the following:
* Limit a requester's UDP payload size.
* Prevent UDP packet fragmentation when DNS responses are >512 bytes.
* Add an EDNS OPT pseudo RR when a client _does not_ specify one.
This commit resolves Bug 1949361, particularly via the 3rd bullet listed
above. When a DNS query bound for an upstream resolver is forwarded without
any EDNS OPT pseudo RR, the upstream resolver may send back packets that
exceed CoreDNS's UDP buffer size, resulting in a SERVFAIL response
(along with various CoreDNS errors being logged).
Note that preventing DNS packet fragmentation may mitigate potential
security vulnerabilities. See https://dnsflagday.net/2020/ for more …
> [release-4.7] Bug 1953097: Corefile: Enable bufsize plugin for all servers

- pkg/operator/controller/controller_dns_configmap.go
- pkg/operator/controller/controller_dns_configmap_test.go
Enable the CoreDNS bufsize plugin (https://coredns.io/plugins/bufsize/)
with a buffer size value of `1232` bytes to accomplish the following:
* Limit a requester's UDP payload size.
* Prevent UDP packet fragmentation when DNS responses are >512 bytes.
* Add an EDNS OPT pseudo RR when a client _does not_ specify one.
This commit resolves Bug 1949361, particularly via the 3rd bullet listed
above. When a DNS query bound for an upstream resolver is forwarded without
any EDNS OPT pseudo RR, the upstream resolver may send back packets that
exceed CoreDNS's UDP buffer size, resulting in a SERVFAIL response
(along with various CoreDNS errors being logged).
Note that preventing DNS packet fragmentation may mitigate potential
security vulnerabilities. See https://dnsflagday.net/2020/ for more …
> [release-4.6] Bug 1955632: Corefile: Enable bufsize plugin for all servers

- pkg/operator/controller/controller_dns_configmap.go
- pkg/operator/controller/controller_dns_configmap_test.go
The CoreDNS bufsize plugin was enabled with a set size
of 1232 bytes in order to ensure that DNS queries bound for
an upstream resolver contain EDNS OPT Resource Records.
This resolved Bug 1949361.
Some DNS Clients, such as Go's built-in stub DNS resolver, are not
capable of handling DNS UDP messages that are larger than 512 bytes
(even if the proper EDNS flags are included in the message).
See https://github.com/golang/go/issues/13561 &
https://github.com/golang/go/issues/6464 accordingly.
This commit configures the bufsize plugin with a reduced bufsize of 512
bytes for all servers to ensure compatibility with primitive DNS
clients.
pkg/operator/controller/controller_dns_configmap.go:
Set bufsize to 512 bytes for all servers.
pkg/operator/controller/controller_dns_configmap_test.go: …
> Bug 1966116: Corefile: Set bufsize to 512 bytes for all servers

- pkg/operator/controller/status/controller.go
Add a watch on daemonsets to the status controller so that it updates status when the daemonset's spec or status changes.
* `pkg/operator/controller/status/controller.go` (`New`): Watch daemonsets.
> Bug 1973482: status: Watch daemonsets

- manifests/0000_70_dns-operator_00-cluster-role.yaml
- pkg/operator/controller/status/controller.go
- test/e2e/operator_test.go
Add a watch on clusteroperators in the status controller so that it updates or recreates the dns clusteroperator as necessary should something else update or delete it.
* `pkg/operator/controller/status/controller.go` (`New`): Watch clusteroperators with a map function and predicate to reconcile `dnses.operator.openshift.io/default` if `clusteroperators.config.openshift.io/dns` is updated.
* test/e2e/operator_test.go (TestOperatorRecreatesItsClusterOperator): New test.  Verify that the operator recreates the "dns" clusteroperator if the clusteroperator is deleted.
> status: Watch clusteroperators

- manifests/0000_90_dns-operator_03_prometheusrules.yaml
This PR addresses the BZ https://bugzilla.redhat.com/show_bug.cgi?id=1992555
> Bug 1992555: Comply with Openshift alerting guidelines

- pkg/operator/controller/controller_dns_service.go
- pkg/operator/controller/controller_dns_service_test.go
When comparing services to determine whether an update is required, treat the empty value and default value for `spec.internalTrafficPolicy` as equal.
Before this change, the update logic would keep trying to revert the default value that the API set for the service's internal traffic policy.
The `spec.internalTrafficPolicy` field is newly enabled in Kubernetes 1.22 (OpenShift 4.9).
* `pkg/operator/controller/controller_dns_service.go` (`serviceChanged`): Use the new `cmpServiceInternalTrafficPolicyType` function so that two services are considered equal if the only difference between them is that one does not specify internal traffic policy and the other service has the default value.
(`cmpServiceInternalTrafficPolicyType`): New function.
* …
> Bug 2002461: serviceChanged: Fix internalTrafficPolicy

- pkg/operator/controller/controller_dns_configmap.go
- pkg/operator/controller/controller_dns_configmap_test.go
Forward entries are missing a cache TTL on them, for larger environments with forwarded zones this can lead to heavier then expected load on DNS servers.
> Bug 2006803: Set CoreDNS cache entries for forwarded zones

- pkg/operator/controller/controller_dns_configmap.go
- pkg/operator/controller/controller_dns_configmap_test.go
Before this change, the operator did not enable the "prometheus" plugin in server blocks for custom upstream resolvers.  As a consequence, CoreDNS did not report metrics for upstream resolvers and only reported metrics for the default server block.  This change enables the "prometheus" plugin for all server blocks.
* `pkg/operator/controller/controller_dns_configmap.go` (`corefileTemplate`): Add the "prometheus" plugin to server blocks for custom upstream resolvers.
* `pkg/operator/controller/controller_dns_configmap_test.go` (`TestDesiredDNSConfigmap`): Verify that `desiredDNSConfigMap` enables the "prometheus" plugin for all server blocks.
> Bug 2020489: Enable metrics for custom upstream resolvers

- .gitignore
- pkg/operator/controller/controller_dns_configmap_test.go
- pkg/operator/controller/testdata/1ipv6_and_policy
- pkg/operator/controller/testdata/1ns_and_policy
- pkg/operator/controller/testdata/1ns_no_policy
- pkg/operator/controller/testdata/1sysresconf
- pkg/operator/controller/testdata/5upstreams
- pkg/operator/controller/testdata/debug_loglevel
- pkg/operator/controller/testdata/default_corefile
- pkg/operator/controller/testdata/duplicate_upstreams
- pkg/operator/controller/testdata/empty_upstreams_array
- pkg/operator/controller/testdata/just_policy
- pkg/operator/controller/testdata/mult_upstreamresolvers
- pkg/operator/controller/testdata/normal_loglevel
- pkg/operator/controller/testdata/trace_loglevel
- pkg/operator/controller/testdata/upstreams_type_empty
- pkg/operator/controller/testdata/without_upstreamresolvers
Moving all the test Corefiles from `controller_dns_configmap_test.go` to individual files under `test-corefiles` directory. This improves code readibility and makes it easier to handle the Corefiles. This also removes duplicate Corefiles for multiple cases, and instead use the same file for all the relevant cases.
Co-authored-by: Chad Scribner <chad@redhat.com>
> NE-815 Extract test Corefiles inside DNS ConfigMap test to individual files

- manifests/0000_70_dns-operator_02-deployment-ibm-cloud-managed.yaml
- manifests/0000_70_dns-operator_02-deployment.yaml
Starting from OpenShift 4.11 pod security admission is being activated. In OpenShift the default pod security admission level is going to be `restricted`. This PR fixes workloads from this repository. Concretely, the following violations have been detected:
```
{
  "objectRef": "openshift-dns-operator/deployments/dns-operator",
  "pod-security.kubernetes.io/audit-violations": "would violate PodSecurity \"restricted:latest\": allowPrivilegeEscalation != false (containers \"dns-operator\", \"kube-rbac-proxy\" must set securityContext.allowPrivilegeEscalation=false), unre
stricted capabilities (containers \"dns-operator\", \"kube-rbac-proxy\" must set securityContext.capabilities.drop=[\"ALL\"]), runAsNonRoot != true (pod or containers \"dns-operator\", \"kube-rbac-proxy\" must set …
```
> AUTH-182: manifests/deployment: comply to restricted pod security level

- pkg/operator/controller/controller_dns_service.go
- pkg/operator/controller/controller_dns_service_test.go
Currently DNS traffic in openshift can go to any random pod on any host in any zone. Traffic should at a minimum be prefered to stay within a zone to prevent latency and reduce failure points in a given dns request. This requiresOpenshift 4.11 or TopologyAwareHints feature gate to be enabled.
> Bug 2095941: topology aware hints to prefer to keep dns traffic within a zone

- pkg/operator/controller/controller.go
- pkg/operator/controller/controller_cabundle_configmap.go
- pkg/operator/controller/controller_cabundle_configmap_test.go
- pkg/operator/controller/controller_dns_configmap.go
- pkg/operator/controller/controller_dns_configmap_test.go
- pkg/operator/controller/controller_dns_daemonset.go
- pkg/operator/controller/controller_dns_daemonset_test.go
- pkg/operator/controller/testdata/tls_with_non_existing_cabundle
- test/e2e/operator_test.go
- test/e2e/utils.go
* Fixes a nil pointer error that was crashing the operator when configuring DNS-over-TLS with a configmap that does not exist.
* Simplifies some of the configmap management logic.
* Adds a corresponding e2e test.
> Bug 2092509: Append an error when a non-existent configmap is configured for DNS-over-TLS

- .github/ISSUE_TEMPLATE/config.yml
- README.md
Update Bugzilla links that reference the "DNS" component to instead use the "Networking" component and "DNS" subcomponent.
* `.github/ISSUE_TEMPLATE/config.yml`:
* `README.md`: Update Bugzilla links.
> DPP-10859: Update Bugzilla links to "Networking" component

- go.mod
- test/e2e/operator_test.go
- test/e2e/utils.go
This fixes the e2e breakage introduced with the recent adjustment of the default security policy.
* Adds a `SecurityContext` configuration to `upstreamContainer()` as that's used by both `TestDNSForwarding` and `TestDNSOverTLSForwarding`. The configuration is standard with one exception; `RunAsNonRoot: false` is needed because we're using `cluster-dns-operator`'s CoreDNS image which runs as root in the container.
* Switches the dns-over-tls test namespace to `openshift-testdnsovertls` as a workaround to the pod security autolabeling.
* Adds a volume mode to `upstreamTLSPod()` to match `upstreamPod()` as the lack of the volume mode seemed to stop the test pods from starting.
> OCPBUGS-360: Pod security policy change breaks DNS forwarding e2e tests

- test/e2e/operator_test.go
- test/e2e/utils.go
* Simplifies `TestDNSOverTLSForwarding`
* Adds the needed SecurityContext for `TestDNSForwarding` to succeed
* Moves the client pods for `TestDNSOverTLSForwarding` and `TestDNSForwarding` to privileged namespaces.
> OCPBUGS-873: Address e2e failures due to pod security

- pkg/operator/controller/controller_dns_configmap.go
- pkg/operator/controller/testdata/1ipv6_and_policy
- pkg/operator/controller/testdata/1ns_and_policy
- pkg/operator/controller/testdata/1ns_no_policy
- pkg/operator/controller/testdata/1sysresconf
- pkg/operator/controller/testdata/5upstreams
- pkg/operator/controller/testdata/debug_loglevel
- pkg/operator/controller/testdata/default_corefile
- pkg/operator/controller/testdata/duplicate_upstreams
- pkg/operator/controller/testdata/empty_upstreams_array
- pkg/operator/controller/testdata/forwardplugin_tls
- pkg/operator/controller/testdata/just_policy
- pkg/operator/controller/testdata/mult_upstreamresolvers
- pkg/operator/controller/testdata/normal_loglevel
- pkg/operator/controller/testdata/tls_with_non_existing_cabundle
- pkg/operator/controller/testdata/trace_loglevel
- pkg/operator/controller/testdata/upstreamresolvers_with_cabundle
- pkg/operator/controller/testdata/upstreams_type_empty
- pkg/operator/controller/testdata/without_upstreamresolvers
Turns on the `chaos` CoreDNS plugin (https://coredns.io/plugins/chaos/) that exposes some metadata that can help debugging in the future.
The regression https://issues.redhat.com/browse/OCPBUGS-488 found in 4.10 has exposed a CI test gap in local DNS endpoint preference and this plugin would allow a new CI tests to determine what CoreDNS pod is replying to a query so we can determine it is indeed the local DNS endpoint.
> NE-1066: Enable the chaos plugin for CoreDNS in order to expose CoreDNS metadata

- pkg/operator/controller/controller.go
- pkg/operator/controller/controller_test.go
- pkg/operator/controller/names.go
The DNS namespace manifest has been updated, and changes need to be applied during the controller reconcile.  Add all the required labels to a set and compare the existing namespace labels to this set.  If they don't match, change them and update the namespace.  Add a unit test.
NamespaceRunLevelLabel           = "openshift.io/run-level"    
NamespaceClusterMonitoringLabel  = "openshift.io/cluster-monitoring" 
NamespacePodSecurityEnforceLabel = "pod-security.kubernetes.io/enforce"
NamespacePodSecurityAuditLabel   = "pod-security.kubernetes.io/audit" 
NamespacePodSecurityWarnLabel    = "pod-security.kubernetes.io/warn"
> OCPBUGS-1549: Reconcile the DNS namespace

- test/e2e/operator_test.go
* Moves `TestDNSLogging` further up the chain so it isn't affected by the daemonset churn.
* Some minor test tweaks to improve the run time.
> OCPBUGS-1439: Fix TestDNSLogging race condition

- pkg/operator/controller/controller_dns_daemonset.go
- pkg/operator/controller/controller_dns_daemonset_test.go
- test/e2e/operator_test.go
When adding the enable DaemonSet eviction annotation `cluster-autoscaler.kubernetes.io/enable-ds-eviction`, do not overwrite other annotations.  Fix missing managed annotation - `target.workload.openshift.io/management`. Fix unit tests. Add e2e test.
modified:   pkg/operator/controller/controller_dns_daemonset.go
modified:   pkg/operator/controller/controller_dns_daemonset_test.go
modified: test/e2e/operator_test.go
> OCPBUGS-753: keep dns-default annotations intact

- .ci-operator.yaml
- Dockerfile
- pkg/manifests/bindata.go
Reconciling with https://github.com/openshift/ocp-build-data/tree/b44f15ec9e84d1831eac81f8c757b3bed985dbeb/images/ose-cluster-dns-operator.yml
This PR is based on #331 but additionally includes changes to the formatting of `pkg/manifests/bindata.go` that result from using the updated Go 1.19 builder image.  Including these changes is necessary in order for the verify job to pass.
> Updating ose-cluster-dns-operator images to be consistent with ART, and generate bindata

- pkg/operator/controller/controller_dns_daemonset.go
- pkg/operator/controller/controller_dns_daemonset_test.go
- test/e2e/operator_test.go
Annotate DNS pods to enable the cluster autoscaler to evict them when scaling down a node.
Before this change, node scale-in could cause DNS disruption for tainted nodes.  If a node is tainted such that it has no DNS pod, then DNS queries originating on that node are forwarded to DNS pods on other nodes.  If one of these nodes was removed by scale-in or otherwise, the DNS pod on that node would be abruptly removed when the node shut down, and it would take some time for the node lifecycle controller to mark the pod as not ready, then for the endpoints controller and endpointslice controller to remove the pod's endpoint, and then for the service proxy to stop forwarding queries to the pod.  This delay could cause DNS lookup failures when queries were sent to a pod that had been on a …
> [release-4.10] OCPBUGS-2602: Allow autoscaler to evict DNS pods

- test/e2e/operator_test.go
- test/e2e/utils.go
Previously, the test started a pod to issue 'dig' queries from and then fetched the list of coredns pods. For each coredns pod, a 'dig' request was made, and logs for the "dns" container were retrieved to assert that logging was both enabled and working by matching the expected dig query failure (because the host queried does not exist) in the logging output from coredns.
However, queries from any pod will use/target the coredns pod on the same node, leading to potential failures when the first checked coredns pod isn't on the same node as the test pod.
The test has been reworked to remove the test pod and execute the following command for each coredns pod found:
oc exec <coredns-pod> -- dig @localhost -p 5353 <hostname>
Existing test assertions remain unchanged; the "dns" container logs …
> OCPBUGS-12859: deflake TestDNSLogging

- cmd/dns-operator/main.go
- go.mod
Due to controller-runtime v0.15.0 bump and changes made in https://github.com/kubernetes-sigs/controller-runtime/pull/2317, you must set a logger for controller-runtime. We have our own, so we will set controller-runtime's logger to Null.
`cmd/dns-operator/main.go`: Set a null logger for controller runtime on startup.
`go.mod`: `go mod tidy` update. Move logr from indirect to direct
dependency.
> OCPBUGS-14395: Set controller-runtime logger to a null logger

- .github/ISSUE_TEMPLATE/config.yml
- OWNERS
- README.md
* `.github/ISSUE_TEMPLATE/config.yml`: Update the Bugzilla link to point instead to the Red Hat Issue Tracker.
* `Owners`: Remove the component field.  Add past approvers to `emeritus_approvers` and remove them from the `approvers` and `reviewers` lists.
* `README.md`: Update the Bugzilla link.
---
This PR is similar to https://github.com/openshift/cluster-ingress-operator/pull/916 and https://github.com/openshift/cluster-ingress-operator/pull/968.
> OCPBUGS-12863: Replace Bugzilla link with Red Hat Issue Tracker

- pkg/operator/controller/controller_dns_configmap.go
- pkg/operator/controller/testdata/1ipv6_and_policy
- pkg/operator/controller/testdata/1ns_and_policy
- pkg/operator/controller/testdata/1ns_no_policy
- pkg/operator/controller/testdata/1sysresconf
- pkg/operator/controller/testdata/5upstreams
- pkg/operator/controller/testdata/debug_loglevel
- pkg/operator/controller/testdata/default_corefile
- pkg/operator/controller/testdata/default_corefile_cache_configured
- pkg/operator/controller/testdata/default_corefile_cache_with_fractional_values_configured
- pkg/operator/controller/testdata/default_corefile_no_cache_configured
- pkg/operator/controller/testdata/duplicate_upstreams
- pkg/operator/controller/testdata/empty_upstreams_array
- pkg/operator/controller/testdata/forwardplugin_protocolstrategy_none
- pkg/operator/controller/testdata/forwardplugin_protocolstrategy_tcp
- pkg/operator/controller/testdata/forwardplugin_tls
- pkg/operator/controller/testdata/just_policy
- pkg/operator/controller/testdata/mult_upstreamresolvers
- pkg/operator/controller/testdata/normal_loglevel
- pkg/operator/controller/testdata/tls_with_non_existing_cabundle
- pkg/operator/controller/testdata/trace_loglevel
- pkg/operator/controller/testdata/upstreamresolver_protocolstrategy_none
- pkg/operator/controller/testdata/upstreamresolver_protocolstrategy_tcp
- pkg/operator/controller/testdata/upstreamresolvers_with_cabundle
- pkg/operator/controller/testdata/upstreams_type_empty
- pkg/operator/controller/testdata/without_upstreamresolvers
As endorsed at [DNS Flag Day](http://www.dnsflagday.net/2020/), the DNS Community recommends a bufsize setting of 1232 as a safe default that supports larger payloads, while generally avoiding IP fragmentation on most networks. This is particularly relevant for payloads like those generated by DNSSEC, which tend to be larger.
Previously, CoreDNS always used the EDNS0 extension, which enables UDP-based DNS queries to exceed 512 bytes, when CoreDNS forwarded DNS queries to an upstream name server, and so OpenShift specified a bufsize setting of 512 to maintain compatibility with applications and name servers that did not support the EDNS0 extension.
For clients and name servers that do support EDNS0, a bufsize setting of 512 can result in more DNS truncation and unnecessary TCP …
> OCPBUGS-15605: Update bufsize to 1232 bytes

- pkg/operator/controller/dns_status.go
- pkg/operator/controller/status/controller.go
From [the API docs][1]:
lastTransitionTime is the time of the last update to the current status property.
And [the library-go `SetStatusCondition` implementation][2] includes:
```go
if existingCondition.Status != newCondition.Status {
existingCondition.Status = newCondition.Status
existingCondition.LastTransitionTime = metav1.NewTime(time.Now())
}
existingCondition.Reason = newCondition.Reason
existingCondition.Message = newCondition.Message
```
The motivation for that behavior is that it's often more useful to know "how long has this resource been `Degraded=True`?" and similar than it is to know how long it has had exactly the same `status`/`reason`/`message`. Messages in particular can be fairly mutable (`# of # pods available`, etc.), and changes there do not necessarily represent …
> OCPBUGS-18034: Only bump lastTransitionTime on 'status' changes

- test/e2e/operator_test.go
Set a null logger for controller-runtime in the E2E tests.
Controller-runtime v0.15.0 added a check that prints an error message and a stack trace if no logger is initialized.
* `test/e2e/operator_test.go` (`init`): Initialize the logger for controller-runtime.
Fix two log lines that logged error values that are always nil.
* `test/e2e/operator_test.go` (`TestCoreDNSDaemonSetReconciliation`): Don't log nil error values.
> OCPBUGS-19510: test/e2e: Set controller-runtime logger

- pkg/manifests/assets/dns/daemonset.yaml
- pkg/operator/controller/controller_dns_daemonset.go
- pkg/operator/controller/controller_dns_daemonset_test.go
The defect in the daemon controller, [OCPBUGS-19452](https://issues.redhat.com/browse/OCPBUGS-19452) that prevented us from using `maxSurge` has been fixed by https://github.com/openshift/kubernetes/pull/1716.
This reverts #379.
> OCPBUGS-20024: Revert "Revert "Set DNS DaemonSet's maxSurge value to 10%""

- pkg/operator/controller/controller_dns_node_resolver_daemonset.go
- pkg/operator/controller/dns_status.go
- pkg/operator/controller/dns_status_test.go
Followup to PR #384.
- pkg/operator/controller/controller_dns_node_resolver_daemonset.go - small update to a comment
- pkg/operator/controller/dns_status.go - hardcode maxUnavailable to 10% of desiredNumberScheduled and remove condition "invalid maxUnavailable value"
- pkg/operator/controller/dns_status_test.go - remove maxUnavailable format testing
> OCPBUGS-20024: Ignore max unavailable for status

- manifests/0000_70_dns-operator_02-deployment-ibm-cloud-managed.yaml
- manifests/0000_70_dns-operator_02-deployment.yaml
- pkg/manifests/assets/dns/daemonset.yaml
All openshift operators must include FallbackToLogsOnError to ease debugging.
> OCPBUGS-28230: add FallbackToLogsOnError for easier debugging

- manifests/0000_70_dns-operator_00-cluster-role.yaml
#393 added RBAC for featuregates in the cluster role for dns operator as well as `configInformers.Config().V1().FeatureGates()` call in the dns operator in 4.16. This caused issues during upgrade of hypershift clusters from 4.15 to 4.16 as sometimes the deployment of the cluster dns operator may get upgraded before the cluster role which caused the dns operator to crashloop (by design) temporarily during the upgrade. This PR adds the required RBAC to the cluster role in 4.15 so that the dns operator doesn't crashloop (by design) during the upgrade of hypershift clusters from 4.15 to 4.16.
> OCPBUGS-32093: Add RBAC related to featuregates to fix hypershift upgrade

- .ci-operator.yaml
- Dockerfile
- go.mod
- go.sum
A copy of #401, plus an update to go.sum done with `go mod tidy` to fix the verify job.
---
Updating ose-cluster-dns-operator-container image to be consistent with ART for 4.16
TLDR:
Product builds by ART can be configured for different base and builder images than corresponding CI
builds. This automated PR requests a change to CI configuration to align with ART's configuration;
please take steps to merge it quickly or contact ART to coordinate changes.
The configuration in the following ART component metadata is driving this alignment request:
[ose-cluster-dns-operator.yml](https://github.com/openshift/ocp-build-data/tree/a68ac2d64a2e3bcf927ae39410024a4c1140177a/images/ose-cluster-dns-operator.yml).
Detail:
This repository is out of sync with the downstream product builds for this …
> OCPBUGS-27924: Updating ose-cluster-dns-operator-container image to be consistent with ART for 4.16

- go.mod
- go.sum
- pkg/operator/controller/controller_cluster_role.go
- vendor/github.com/openshift/coredns-ocp-dnsnameresolver/operator/controller/dnsnameresolver/resolver.go
- vendor/modules.txt
This PR bumps the version of the the DNSNameResolver controller. This PR also adds the additional RBAC permissions required by the CoreDNS pods for the DNSNameResolver CRs.
> OCPBUGS-33750: Bump version of DNSNameResolver controller

- go.mod
- go.sum
- pkg/operator/controller/controller_cluster_role.go
- vendor/github.com/openshift/coredns-ocp-dnsnameresolver/operator/controller/dnsnameresolver/resolver.go
- vendor/modules.txt
This PR bumps the version of the the DNSNameResolver controller for release-4.16. This PR also adds the additional RBAC permissions required by the CoreDNS pods for the DNSNameResolver CRs.
> [release-4.16] OCPBUGS-37078: Bump version of DNSNameResolver controller

- pkg/manifests/assets/dns/daemonset.yaml
Missed the kube-rbac-proxy container in #439
> OCPBUGS-59781: Read only root filesystem
