openshift/cluster-dns-operator

pkg/stub/handler.go
- ClusterDNS specific resources are tied to its daemonset as owner ref
so that deletion of this daemonset will trigger deletion of corresponding
configmap and service resources.
=>  Changed delete handling to use garbage collection

images/cluster-dns-operator/Dockerfile
Convert the Dockerfile to multistage for pipeline build style conformance.
=> Use multistage Dockerfile

Makefile
ref https://github.com/openshift/cluster-nfd-operator/pull/2#issue-235099502
=> Makefile: don't specify GOARCH

pkg/stub/handler.go
- This will maintain backward compatibility with openshift 3.x
=> Bug 1678472: Create external name service default/openshift to resolve 'openshift.default.svc' to 'kubernetes.default.svc'

pkg/operator/controller/status.go
Previously, `clusteroperator/dns` was being created without `status`. Even though the resource was being created with status fields properly constructed and included in the `client.create` call, the resource is initially created without `status`. `clusteroperator/dns` must be created first, then have the status updated.
=> Bug 1699488: Fixes DNS ClusterOperator Initial Status

pkg/operator/controller/status.go, pkg/operator/controller/status_test.go
* `pkg/operator/controller/status.go`:
* `pkg/operator/controller/status_test.go` (`syncOperatorStatus`): Pass old versions to `computeOperatorStatusConditions`.
(`computeOperatorStatusConditions`): Pass old versions to `computeOperatorProgressingCondition`.
(`computeOperatorProgressingCondition`): Add "Upgraded x to y" message if old and current versions of an image do not match.
(`TestComputeOperatorStatusConditions`): Add test cases.
=> Bug 1690342: Update Progressing condition if upgrade happened

pkg/operator/controller/status.go
Fix-up to https://github.com/openshift/cluster-dns-operator/pull/104.
* `pkg/operator/controller/status.go` (`computeOperatorProgressingCondition`): Move the check for a mismatch between old version and reported version before the check for a mismatch between current version and reported version.  Make sure to use the right string for the condition's message.
=> Bug 1690342: Fix Progressing condition upgrade check

pkg/operator/controller/status.go, pkg/operator/controller/status_test.go
If any DNS resource's degraded condition is true, set the clusteroperator's degraded condition to be true as well.
Note: An implication of this change is that the clusteroperator will report degraded true during upgrades.
* `pkg/operator/controller/status.go` (`dnsStatusConditionsCounts`): New struct type.  Define a field for each status condition, to count how many DNSes have that condition, as well as field for the total number of DNSes.
(`syncOperatorStatus`): Use `computeDNSStatusConditionCounts` to get a `dnsStatusConditionsCounts` value, and pass this value to `computeOperatorStatusVersions` and `computeOperatorStatusConditions`.  Delete the `dnsesTotal`, `dnsesAvailable`, and `allDNSesAvailable` variables.
(`computeDNSStatusConditionCounts`): New function.  Take a slice of DNSes …
=> Bug 1711364: Report operator is degraded if any DNS is degraded

pkg/operator/controller/controller_dns_daemonset.go, pkg/operator/controller/controller_dns_daemonset_test.go
* `pkg/operator/controller/controller_dns_daemonset.go` (`daemonsetConfigChanged`): Compare the node selector.  Set the node selector in the updated daemonset.
* `pkg/operator/controller/controller_dns_daemonset_test.go` (`TestDaemonsetConfigChanged`): Add tests for `daemonsetConfigChanged`.
=> daemonsetConfigChanged: Check node selector

HACKING.md, Makefile, hack/buildconfig.yaml, hack/create-buildconfig.sh, hack/start-build.sh
DNS Operator hacking instructions for building the developed operator remotely on the cluster.
=> DNS Operator hacking instructions for building the developed operator remotely on the cluster

Makefile, hack/verify-deps.sh
Ports https://github.com/openshift/cluster-ingress-operator/pull/386 to DNS Operator.
/assign @ironcladlou @knobunc 
/cc @Miciah @frobware
=> Add a dependency verification script

OWNERS
Add myself (candita) to OWNERS
=> addOwners-candita

pkg/operator/controller/status/controller.go, pkg/operator/controller/status/controller_test.go
Report the current `status.versions` value in the clusteroperator while the clusteroperator is reporting `Progressing=True` so that the clusteroperator doesn't report versions before it has finished upgrading to them.
* `pkg/operator/controller/status/controller.go` (`Reconcile`): Compute `newVersions` and pass it to `computeOperatorProgressingCondition` and `computeOperatorStatusVersions`.  Also pass the clusteroperator's newly computed `Progressing` status condition to `computeOperatorStatusVersions`.
(`computeOperatorStatusVersions`): Delete the `haveDNS` and `dns` parameters and the logic that checked the dns's `Progressing` status condition.  In their place, add a parameter for the clusteroperator's `Progressing` status condition, and use this status condition to decide whether to …
=> Bug 1952174: status: Report old versions while progressing

pkg/operator/controller/status/controller.go
This is a manual cherry-pick of #283.  I am creating the PR manually so that it can be tested in parallel to #283.
=> [release-4.8] Bug 1974978: status: Watch daemonsets

go.mod, go.sum, pkg/operator/controller/controller_dns_configmap.go, pkg/operator/controller/controller_dns_configmap_test.go, vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk, vendor/github.com/openshift/build-machinery-go/make/targets/openshift/images.mk, vendor/github.com/openshift/build-machinery-go/make/targets/openshift/kustomize.mk, vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk, vendor/modules.txt
Fixes 
- https://bugzilla.redhat.com/show_bug.cgi?id=2031685
Found by QE (cc @ShudiLi ) for https://issues.redhat.com/browse/NE-684
=> Bug 2031685: Duplicated forward upstreams should be removed from the dns operator

pkg/operator/controller/controller_dns_configmap.go, pkg/operator/controller/controller_dns_configmap_test.go
when UpstreamResolvers.Upstream.Type=''
=> Bug 2031685: Fix duplicate /etc/resolv.conf in configmap

pkg/operator/controller/controller.go, pkg/operator/controller/dns_status.go, pkg/operator/controller/dns_status_test.go
This is a follow up to:
https://github.com/openshift/cluster-dns-operator/pull/318
When we prevent frequent status updates between True/False for
Progressing, ensure that reconcile will run again in the future for
the specific case where we return the existing condition.
=> Bug 2093236: propagate retry request for progressing updates

pkg/operator/controller/controller_dns_service.go, pkg/operator/controller/controller_dns_service_test.go
Only set the `service.kubernetes.io/topology-aware-hints` annotation on the DNS service if the cluster has valid nodes in at least two different topology zones.
Without this change, a cluster in which all nodes had the same `topology.kubernetes.io/zone` label value would emit "TopologyAwareHintsDisabled" events repeatedly.
Follow-up to #364..
* `pkg/operator/controller/controller_dns_service.go` (`shouldEnableTopologyAwareHints`): Check that the number of zones (not just nodes) is >= 2.
* `pkg/operator/controller/controller_dns_service_test.go` (`Test_shouldEnableTopologyAwareHints`): Amend test cases to include multiple zones.
=> OCPBUGS-24602: Enable topology-aware hints iff nodes in >=2 zones

manifests/0000_90_dns-operator_03_prometheusrules.yaml
Issue: 
- https://issues.redhat.com/browse/OCPBUGS-51193
=> OCPBUGS-51193: Add runbook_url for CoreDNSErrorsHigh

manifests/0000_90_dns-operator_03_prometheusrules.yaml
Issue: 
- https://issues.redhat.com/browse/OCPBUGS-52497
=> OCPBUGS-52497: [release-4.17] Add runbook_url for CoreDNSErrorsHigh

manifests/0000_90_dns-operator_03_prometheusrules.yaml
Issue: 
- https://issues.redhat.com/browse/OCPBUGS-52498
=> OCPBUGS-52498: [release-4.16] Add runbook_url for CoreDNSErrorsHigh

manifests/0000_90_dns-operator_03_prometheusrules.yaml
Issue: 
- https://issues.redhat.com/browse/OCPBUGS-52499
=> OCPBUGS-52499: [release-4.15] Add runbook_url for CoreDNSErrorsHigh

manifests/0000_90_dns-operator_03_prometheusrules.yaml
Issue: 
- https://issues.redhat.com/browse/OCPBUGS-52500
=> OCPBUGS-52500: [release-4.14] Add runbook_url for CoreDNSErrorsHigh
